spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chat_app
      username: chatbot
      password: chatbot
      authentication-database: admin

server:
  port: ${PORT:8088}