spring:
  data:
    mongodb:
      uri: mongodb+srv://chatuser:chat123@cluster0.tdnwj1v.mongodb.net/chatdb?retryWrites=true&w=majority

  main:
    allow-bean-definition-overriding: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration